TOKEN = "YOUR_BOT_TOKEN"
MONGODB = "YOUR_MONGODB_TOKEN"
DATABASE = "YOUR_DATABASE_NAME"
COLLECTION = "YOUR_COLLECTION_NAME_FOR_USERS"
COLLECTION2 = "YOUR_COLLECTION_NAME_FOR_PROMOCODES"
admin_id = YOUR_TELEGRAM_ID
